const express = require('express');
const router = express.Router();

router.get('/', (req, res, next) => {
    res.send('get users');
});

router.get('/:uid', (req, res, next) => {
    const {uid} = req.params;
    res.send('get user: '+uid);
});

router.post('/', (req, res, next) => {
    res.send('create user > uid will be generated by server');
});

router.post('/:uid', (req, res, next) => {
    const {uid} = req.params;
    res.send('create user with uid: ' + uid);
});

router.put('/', (req, res, next) => {
    res.send('update(=>replace all users');
});

router.put('/:uid', (req, res, next) => {
    const {uid} = req.params;
    res.send('update(or upsert) user: ' + uid);
});

router.put('/', (req, res, next) => {
    res.send('update(=>replace all users');
});

router.put('/:uid', (req, res, next) => {
    const {uid} = req.params;
    res.send('update(or upsert) user: ' + uid);
});

router.delete('/', (req, res, next) => {
    res.send('delete all users');
});

router.delete('/:uid', (req, res, next) => {
    const {uid} = req.params;
    res.send('delete user: ' + uid);
});

module.exports = router

